const NAMES_LIMIT = 300;
const INITIAL_POINTS = 10;
const GENDER_API_KEY =   "eTsWHefpumSeEAlLEzTsuBu9U7E2sdKPM73n";
const MIXED_VALUE = 60;
module.exports ={NAMES_LIMIT, INITIAL_POINTS, GENDER_API_KEY, MIXED_VALUE}
